spring.application.name=LeaveManagementSystem

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/leave_management_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Changepass@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# DATA INITIALIZATION
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true